name: '📦 依存関係のインストール'
description: 'Node.jsのセットアップと依存関係のインストールを行う共通アクション'

inputs:
  node-version:
    description: 'Node.jsのバージョン'
    required: false
    default: '20'

runs:
  using: "composite"
  steps:
    - name: 🔧 Node.js環境のセットアップ
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    
    - name: 📦 依存関係のインストール
      shell: bash
      run: npm ci 
