name: "🚀 api-server"

on:
  push:
    branches: [main, feature/*]
    paths:
      - "apps/api-server/**"
      - "packages/**"
      - "turbo.json"
      - "package.json"
  pull_request:
    paths:
      - "apps/api-server/**"
      - "packages/**"
      - "turbo.json"
      - "package.json"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 コードのチェックアウト
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🏗️ ビルド＆テスト
        uses: ./.github/actions/build-and-test
        with:
          package-filter: api-server
          node-version: "20"
