name: "🚀 本番環境へデプロイ"

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: "20"
  PNPM_VERSION: "9.15.1"

permissions:
  contents: read
  deployments: write

jobs:
  deploy-production:
    name: 🏭 本番デプロイ
    runs-on: ubuntu-latest
    steps:
      - name: 📥 コードのチェックアウト
        uses: actions/checkout@v4

      - name: 📦 依存関係のインストール
        uses: ./.github/actions/install-dependencies
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 🔧 Vercel CLIのインストール
        run: npm install --global vercel@latest

      - name: 🌐 Beatfolio環境情報の取得
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BEATFOLIO_PROJECT_ID }}

      - name: 🔍 Beatfolio環境変数の設定
        run: |
          vercel env rm DEBUG_URL production --yes --token=${{ secrets.VERCEL_TOKEN }} || true
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BEATFOLIO_PROJECT_ID }}

      - name: 🏗️ Beatfolioビルド
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BEATFOLIO_PROJECT_ID }}

      - name: 🚀 Beatfolioデプロイ
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BEATFOLIO_PROJECT_ID }}

      - name: 🌐 APIサーバー環境情報の取得
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_API_SERVER_PROJECT_ID }}

      - name: 🔍 APIサーバー環境変数の設定
        run: |
          vercel env rm DEBUG_URL production --yes --token=${{ secrets.VERCEL_TOKEN }} || true
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_API_SERVER_PROJECT_ID }}

      - name: 🏗️ APIサーバービルド
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_API_SERVER_PROJECT_ID }}

      - name: 🚀 APIサーバーデプロイ
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_API_SERVER_PROJECT_ID }}
