name: "🚀 本番環境へデプロイ"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-production:
    name: 🏭 本番デプロイ
    runs-on: ubuntu-latest
    steps:
      - name: 📥 コードのチェックアウト
        uses: actions/checkout@v4

      - name: 📦 依存関係のインストール
        uses: ./.github/actions/install-dependencies
        with:
          node-version: "20"

      - name: 🏗️ アプリケーションのビルド
        run: npx turbo run build

      - name: 🚀 Beatfolioの本番デプロイ
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BEATFOLIO_PROJECT_ID }}
        working-directory: ./apps/beatfolio
        run: npx vercel deploy --prod --yes --token=${VERCEL_TOKEN}

      - name: 🚀 APIサーバーの本番デプロイ
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_API_SERVER_PROJECT_ID }}
        working-directory: ./apps/api-server
        run: npx vercel deploy --prod --yes --token=${VERCEL_TOKEN}
