name: "🚀 プロジェクトをデプロイ (デバッグ)"

on:
  workflow_dispatch: # 手動実行のみ

jobs:
  debug-build-artifacts:
    name: 🔍 ビルド成果物デバッグ
    runs-on: ubuntu-latest
    steps:
      - name: 📥 コードのチェックアウト
        uses: actions/checkout@v4

      - name: 📦 依存関係のインストール
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: 📦 パッケージインストール
        run: npm ci

      - name: 🏗️ 全体ビルド
        run: npx turbo run build

      # プロジェクト構造の確認
      - name: 📂 プロジェクト構造を確認
        run: |
          echo "==== プロジェクトのルートディレクトリ構造 ===="
          ls -la

          echo "==== apps ディレクトリの構造 ===="
          ls -la apps/

          echo "==== beatfolio ディレクトリの構造 ===="
          ls -la apps/beatfolio/

          echo "==== api-server ディレクトリの構造 ===="
          ls -la apps/api-server/

      # ビルド成果物の確認
      - name: 📂 ビルド成果物の場所を検索
        run: |
          echo "==== beatfolio の .next ディレクトリを探す ===="
          find apps/beatfolio -name ".next" -type d | xargs -I{} ls -la {}

          echo "==== api-server の .next ディレクトリを探す ===="
          find apps/api-server -name ".next" -type d | xargs -I{} ls -la {}

          echo "==== Next.js の出力ディレクトリを検索 ===="
          find apps -name "out" -type d | xargs -I{} ls -la {}

          echo "==== package.json 内の build スクリプトを確認 ===="
          cat apps/beatfolio/package.json | grep "\"build\""
          cat apps/api-server/package.json | grep "\"build\""

      # ビルドログの詳細確認
      - name: 🔍 詳細なビルドログ
        run: |
          echo "==== Beatfolio の詳細ビルド ===="
          cd apps/beatfolio
          npm run build -- --verbose

          echo "==== API Server の詳細ビルド ===="
          cd ../api-server
          npm run build -- --verbose

      # turbo.json の確認
      - name: 📄 turbo.json の内容確認
        run: |
          echo "==== turbo.json の内容 ===="
          cat turbo.json

      # アーティファクトのアップロード
      - name: 📤 beatfolioビルドのアップロード確認
        run: |
          if [ -d "apps/beatfolio/.next" ]; then
            echo "✅ apps/beatfolio/.next ディレクトリが存在します"
            echo "==== ディレクトリの内容 ===="
            ls -la apps/beatfolio/.next
          else
            echo "❌ apps/beatfolio/.next ディレクトリが見つかりません"
            echo "ビルド出力の場所を確認してください"
          fi

      - name: 📤 APIサーバービルドのアップロード確認
        run: |
          if [ -d "apps/api-server/.next" ]; then
            echo "✅ apps/api-server/.next ディレクトリが存在します"
            echo "==== ディレクトリの内容 ===="
            ls -la apps/api-server/.next
          else
            echo "❌ apps/api-server/.next ディレクトリが見つかりません"
            echo "ビルド出力の場所を確認してください"
          fi
